fix the top navigation
hyperjumptech/monika-notification-engine pull request #7
Opened 2023-05-29 07:56 UTC by herenacreative

![localhost_3000__tab=register(iPhone SE)](https://github.com/hyperjumptech/monika-notification-engine/assets/47026826/006cee5c-7673-435f-9e6c-8dee00a91b8c)
<img width="1437" alt="Screen Shot 2023-05-29 at 14 52 08" src="https://github.com/hyperjumptech/monika-notification-engine/assets/47026826/89282b6b-d2db-411f-b7d1-4203ae99d6eb">

2023-05-29 08:12 UTC, nicnocquee requested changes

2023-05-29 08:12 UTC, nicnocquee commented on components/header/index.tsx
> +                <a
Please keep using Link

2023-05-30 03:28 UTC, herenacreative commented on components/header/index.tsx
> +                <a
updated

2024-04-30 11:22 UTC, raosan commented
closing because new fix is simpler #10

2024-04-30 11:23 UTC, raosan commented
closing because new fix is simpler #10

2024-04-30 11:23 UTC, closed without merging